# This file is currently used for dev testing.
[[routes]]
path = "/apiA"
groupId = "groupA

[[routes]]
path = "/apiB"
groupId = "groupB

[[backendGroups]]
groupId = "groupA
[[backendGroups.backends]]
url = "http://localhost:8081"
health = "/health"

[[backendGroups.backends]]
url = "http://localhost:8083"
health = "/health"

[[backendGroups]]
groupId  "groupB"
[[backendGroups.backends]]
url = "http://localhost:8082"
health = "/health"

[[backendGroups.backends]]
url = "http://localhost:8084"
health = "/health"

[[backendGroups.backends]]
url = "http://localhost:8085"
health = "/health"

[rateLimiter]
type = "none"
#type = "fixed_window"  # can be "fixed_window", "token_bucket", "none"
#limit = 100
#window = "1m"

[loadbalancer]
address = ":8443"
cert_file = "cert.pem"
key_file = "key.pem"

[healthchecker]
healthyserver_freq = "20s"
unhealthyserver_freq = "5s"