# This file is currently used for dev testing.
[[routes]]
path = "/apiA"
[[routes.backends]]
url = "http://backend1:8081"
health = "/health"

[[routes.backends]]
url = "http://backend3:8083"
health = "/health"

[[routes]]
path = "/apiB"
[[routes.backends]]
url = "http://backend2:8082"
health = "/health"

[[routes.backends]]
url = "http://backend4:8084"
health = "/health"

[[routes.backends]]
url = "http://backend5:8085"
health = "/health"

[rateLimiter]
type = "none"
#type = "fixed_window"  # can be "fixed_window", "token_bucket", "none"
#limit = 100
#window = "1m"

[loadbalancer]
address = ":8443"
cert_file = "cert.pem"
key_file = "key.pem"

[healthchecker]
healthyserver_freq = "20s"
unhealthyserver_freq = "5s"