name: Performance Benchmarks

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write  # Required to update GitHub Pages
  deployments: write  # Required for GitHub Pages deployment

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.1"

      # Build the project
      - name: Build Project
        run: go build -v ./...

      # Run benchmarks and generate results
      - name: Run Benchmarks
        run: |
          mkdir -p benchmark-results
          go test -bench=. -benchmem -count=10 -run=^$ ./... | tee benchmark-results/current_benchmarks.txt

      # Upload benchmark results to GitHub Pages
      - name: Upload Benchmark Results to GitHub Pages
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: L7LB Go Benchmarks
          tool: 'go'
          output-file-path: benchmark-results/current_benchmarks.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          gh-pages-branch: gh-pages
