name: Performance Benchmarks

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # fetch full history for comparison
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.1"
      
      - name: Install benchmark tools
        run: |
          go install golang.org/x/perf/cmd/benchstat@latest

      - name: Build Project
        run: go build -v ./...

      - name: Run Tests
        run: go test -v ./...

      - name: Prepare Benchmark Results Directory
        run: mkdir -p benchmark-results

      - name: Run Benchmarks on Current Commit
        run: |
          go test -bench=. -benchmem -count=10 ./... | tee benchmark-results/current_benchmarks.txt
          benchstat benchmark-results/current_benchmarks.txt > benchmark-results/current_stats.txt

      - name: Run Benchmarks on Main Branch
        run: |
          git checkout main
          go test -bench=. -benchmem -count=10 ./... | tee benchmark-results/main_benchmarks.txt
          benchstat benchmark-results/main_benchmarks.txt > benchmark-results/main_stats.txt

      - name: Compare Benchmark Statistics
        run: |
          git checkout -
          benchstat main=benchmark-results/main_benchmarks.txt current=benchmark-results/current_benchmarks.txt > benchmark-results/benchmark_comparison.txt
      
      - name: Create Detailed Benchmark Report
        run: |
          echo "## Benchmark Analysis" >> $GITHUB_STEP_SUMMARY
          echo "### Current Commit Benchmark Statistics" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          cat benchmark-results/current_stats.txt >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Benchmark Comparison" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          cat benchmark-results/benchmark_comparison.txt >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

      - name: Upload Benchmark Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: performance-report
          path: benchmark-results/
          retention-days: 30

      - name: Performance Trend Tracking
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: L7LB Go Benchmarks
          tool: 'go'
          output-file-path: benchmark-results/current_benchmarks.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          summary-always: true
          auto-push: true
          gh-pages-branch: 'performance-tracking'